services:
  app:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: app
    networks:
      - my_network

  postgres:
    env_file:
      - .env
    image: postgres:17.2-alpine3.21
    depends_on:
      - app
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5430:5432"
    volumes:
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge

volumes:
  postgres-data:
